# File: ./nginx/nginx-test.conf

# 1. ĐỔI THÀNH $http_x_forwarded_for ĐỂ NHẬN IP GIẢ TỪ K6
limit_req_zone $http_x_forwarded_for zone=global_api_limit:10m rate=50r/s;

upstream nestjs_api {
    server uni-api:3000;
}

server {
    listen 80;

    location /api {
        limit_req zone=global_api_limit burst=100 nodelay;
        limit_req_status 429;

        proxy_pass http://nestjs_api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # 2. TĂNG TIMEOUT LÊN 60s
        # (Khi 12.000 người cùng lao vào khóa DB, các request sẽ phải xếp hàng lâu hơn bình thường. 
        # Nếu không có cái này Nginx sẽ mất kiên nhẫn ném lỗi 504 Gateway Timeout)
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location / {
        proxy_pass http://uni-web:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}