upstream nestjs_api {
    server uni-api:3000;
}

server {
    listen 80;

    # Luồng 1: Nếu gọi vào /api thì đẩy về cụm NestJS
    location /api {
        proxy_pass http://nestjs_api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Luồng 2: Các yêu cầu còn lại đẩy về Next.js Web
    location / {
        proxy_pass http://uni-web:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}