# File: docker-compose.test.yml
version: "3.8"

services:
  nginx:
    volumes:
      # Ánh xạ file test đè lên file mặc định bên trong container
      - ./nginx/nginx-test.conf:/etc/nginx/conf.d/default.conf:ro
